question_data = [{"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "The flag of South Africa features 7 colours.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Greenland is covered with grass and Iceland covered with ice.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "The Republic of Malta is the smallest microstate worldwide.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "There are no roads in\/out of Juneau, Alaska.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Vatican City is a country.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "San Marino is the only country completely surrounded by another country.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "The Southeast Asian island of Borneo is politically divided among 3 countries.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Gothenburg is the capital of Sweden.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "There are no deserts in Europe.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Toronto is the capital city of the North American country of Canada.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "The capital of the US State Ohio is the city of Chillicothe.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "St. Louis is the capital of the US State Missouri.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "You could walk from Norway to North Korea while only passing through Russia.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "hard",
                  "question": "Switzerland has four national languages, English being one of them.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Norway has a larger land area than Sweden.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Tokyo is the capital of Japan.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "New Haven is the capital city of the state of Connecticut in the United States.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "hard",
                  "question": "The two largest ethnic groups of Belgium are Flemish and Walloon. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "There is an island in Japan called \u014ckunoshima, A.K.A. &quot;Rabbit Island&quot;, so named because of it&#039;s huge population of rabbits.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "hard",
                  "question": "Only one country in the world starts with the letter Q.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Is Tartu the capital of Estonia?",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]
